---
- name: Check current timezone
  ansible.builtin.command: timedatectl show
  register: timedatectl_current
  changed_when: false

- name: Set timezone to {{ timezone }}
  ansible.builtin.command: timedatectl set-timezone {{ timezone }}
  changed_when: timezone not in timedatectl_current.stdout
